class Wpr < Formula
  desc "Wallpapers that fit your displays: rotated from folders, generated by shaders"
  homepage "https://github.com/maxwofford/wpr"
  url "https://github.com/maxwofford/wpr/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "e69c41e83c6b2602f3d7105e02634c5543d99c5e6defb6038dffcc00aefd23fb"
  license "MIT"
  head "https://github.com/maxwofford/wpr.git", branch: "main"

  depends_on macos: :sonoma

  def install
    system "swift", "build", "-c", "release", "--disable-sandbox"
    bin.install ".build/release/wpr"
  end

  test do
    assert_match "wallpapers", shell_output("#{bin}/wpr --help")
  end
end
